### ISSUE TITLE
Linie 2 weitere Routen zum Löschen

### ISSUE THREAD

**Issue by Gans100** [Gegreenpeaced/LOTUS-Hannover-FIS#65]
Routen 39 und 40 können weg. Es gibt keinen Start des Y Verkehrs ab Fuhsestraße

**Comment by Gegreenpeaced** [comment]
Ist mit sehr viel Aufwand verbunden... Ich denke ich mache das mal etwas später.

**Comment by Gegreenpeaced** [comment]
done
